micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8082

hello:
  controller:
    path: /hello
  service:
    greeting: Hello from service
  config:
    greeting:
      de: Hallo
      en: Hello